/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
// ServerRequestError struct for ServerRequestError
type ServerRequestError struct {
	Code string `json:"code" xml:"code"`
	Message string `json:"message" xml:"message"`
}
