/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// GENERATED BY JK -- NOT PART OF OPENAPI

package openapi
// ApiProject struct for ApiProject
type ApiJob struct {
	// Job name.
	Name *string `json:"name" xml:"name"`
	// Project name.
	Project *string `json:"project,omitempty" xml:"project"`
	// The source share with which the project will work. This is not required when updating the project.
	Description *string `json:"description,omitempty" xml:"description"`
	// Tags.
	Tags *[]string `json:"tags,omitempty" xml:"tags"`
}
