/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
// ApiPeakTimeSchedule struct for ApiPeakTimeSchedule
type ApiPeakTimeSchedule struct {
	// The numerical day of the week on which to enforce this peak rate limits time window. 0-based with the week starting on Sunday
	DayOfWeek int32 `json:"dayOfWeek" xml:"dayOfWeek"`
	// The number of minutes beyond the start time to enforce the peak time rate limit.
	DurationMinutes int32 `json:"durationMinutes" xml:"durationMinutes"`
	// The start time of peak hours expressed as a time within the day in 24hr format, e.g. 18:30 would be 4:30pm.
	StartTimeHourAndMinutes string `json:"startTimeHourAndMinutes" xml:"startTimeHourAndMinutes"`
}
