/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
// ApiStorageLocationNas Used to create NAS storage locations.
type ApiStorageLocationNas struct {
	// Used to re-activate a 'deleted' storage location.
	Active *bool `json:"active,omitempty" xml:"active"`
	// Sources can have an adGroup name associated with them to restrict access to users not in the group.
	ADGroup *string `json:"aDGroup,omitempty" xml:"aDGroup"`
	// Cost per TB of storage in units of department currency.  Only valid when Department is set.
	CostPerTB *float32 `json:"costPerTB,omitempty" xml:"costPerTB"`
	// ID of department responsible for location storage cost.
	Department *string `json:"department,omitempty" xml:"department"`
	// Description of the storage location.
	Description *string `json:"description,omitempty" xml:"description"`
	// Prevent location from use as a source.
	IsTarget *bool `json:"isTarget" xml:"isTarget"`
	// Used to enable encryption that has been configured for the product.
	EnableEncryption *bool `json:"enableEncryption,omitempty" xml:"enableEncryption"`
	// The limit during off-peak hours, expressed in total number of bytes per second.  Specify 0 for no limit.
	OffPeakBytesPerSecondLimit *float64 `json:"offPeakBytesPerSecondLimit,omitempty" xml:"offPeakBytesPerSecondLimit"`
	// The file scan limit during off-peak hours, expressed in total number of files per second. Specify 0 for no limit.
	OffPeakFilesPerSecondScanLimit *float64 `json:"offPeakFilesPerSecondScanLimit,omitempty" xml:"offPeakFilesPerSecondScanLimit"`
	// Used for NAS locations, this is the filesystem path to the NAS mount point.
	Path *string `json:"path" xml:"path"`
	// The limit during peak hours, expressed in total number of bytes per second.  Specify 0 for no limit.
	PeakBytesPerSecondLimit *float64 `json:"peakBytesPerSecondLimit,omitempty" xml:"peakBytesPerSecondLimit"`
	// The file scan limit during peak hours, expressed in total number of files per second. Specify 0 for no limit.
	PeakFilesPerSecondScanLimit *float64 `json:"peakFilesPerSecondScanLimit,omitempty" xml:"peakFilesPerSecondScanLimit"`
	// A list of the days of the week where rate limits are enforced during peak and off-peak times.  If a day of week is not in the list, it is assumed to be unlimited.
	PeakTimesSchedule *[]ApiPeakTimeSchedule `json:"peakTimesSchedule,omitempty" xml:"peakTimesSchedule"`
	// The number of days to retain files on this target before scheduling files for deletion. This field is only applicable to targets.
	RetentionDays *int32 `json:"retentionDays,omitempty" xml:"retentionDays"`
	Type *string `json:"type" xml:"type"`
}
