/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
// ApiToken struct for ApiToken
type ApiToken struct {
	// The Active Directory domain if applicable.
	Domain string `json:"domain,omitempty" xml:"domain"`
	// The role of the authenticated user.
	Role string `json:"role" xml:"role"`
	// The bearer token to pass via the HTTP Authorization Header in subsequent API commands. For example: Authorization: Bearer 'token'
	Token string `json:"token" xml:"token"`
	// The user login name.
	Username string `json:"username" xml:"username"`
}
