/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
// ApiProjectArchive Project that archives from source to one or more targets.
type ApiProjectArchive struct {
	// Description of the project.
	Description *string `json:"description,omitempty" xml:"description"`
	// The source share the project will archive files off of. This is not required when updating the project.
	Share *string `json:"share" xml:"share"`
	// The directory on the share to archive.  Default is the share root.
	WorkingDirectory *string `json:"workingDirectory,omitempty" xml:"workingDirectory"`
	// Tags to attach to jobs executed by this project.
	Tags *[]string `json:"tags,omitempty" xml:"tags"`
	// Used to re-activate a deactivated project.
	Active *bool `json:"active,omitempty" xml:"active"`
	// Used to pause/resume a project.
	Enabled *bool `json:"enabled,omitempty" xml:"enabled"`
	// The type of archive to perform.
	ProjectType *string `json:"projectType" xml:"projectType"`
	// The action that is performed on the original source file after successful archive.
	BreadCrumbAction *string `json:"breadCrumbAction,omitempty" xml:"breadCrumbAction"`
	// The storage endpoints where files will be archived.
	Targets *[]string `json:"targets" xml:"targets"`
	Filter ApiProjectFilter `json:"filter,omitempty" xml:"filter"`
	Schedule ApiProjectSchedule `json:"schedule" xml:"schedule"`
	Status ApiProjectStatus `json:"status,omitempty" xml:"status"`
}
