/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2023 Spectra Logic Corporation
 *
 * API version: 0.2
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
import (
"time"
)
// ApiFileObjectPaginator struct for ApiFileObjectPaginator
type ApiFileObjectPaginator struct {
	ResultLimit int64 `json:"ResultLimit,omitempty" xml:"ResultLimit"`
	ResultOffset int64 `json:"ResultOffset,omitempty" xml:"ResultOffset"`
	Timestamp time.Time `json:"Timestamp,omitempty" xml:"Timestamp"`
	TotalResults int64 `json:"TotalResults,omitempty" xml:"TotalResults"`
	Data []ApiFileObject `json:"data,omitempty" xml:"data"`
}

