/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
// ApiCredentials struct for ApiCredentials
type ApiCredentials struct {
	// The Active Directory domain if applicable.
	Domain string `json:"domain,omitempty" xml:"domain"`
	// The password for the user.
	Password string `json:"password" xml:"password"`
	// The user login name.
	Username string `json:"username" xml:"username"`
}
