/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
// ApiStorageLocationAmazonS3Glacier Used to create AmazonS3Glacier storage locations.
type ApiStorageLocationAmazonS3Glacier struct {
	// For use only with AmazonS3 Glacier.  The access key ID of the credentials AmazonS3 Glacier.
	AccessKeyId *string `json:"accessKeyId" xml:"accessKeyId"`
	// Used to re-activate a 'deleted' storage location.
	Active *bool `json:"active,omitempty" xml:"active"`
	// Sources can have an adGroup name associated with them to restrict access to users not in the group.
	ADGroup *string `json:"aDGroup,omitempty" xml:"aDGroup"`
	// Used for AmazonS3 Glacier endpoints.  The vault to use for storage.
	Bucket *string `json:"bucket" xml:"bucket"`
	// Cost per TB of storage in units of department currency.  Only valid when Department is set.
	CostPerTB *float32 `json:"costPerTB,omitempty" xml:"costPerTB"`
	// ID of department responsible for location storage cost.
	Department *string `json:"department,omitempty" xml:"department"`
	// Description of the storage location.
	Description *string `json:"description,omitempty" xml:"description"`
	// Used to enable encryption that has been configured for the product.
	EnableEncryption *bool `json:"enableEncryption,omitempty" xml:"enableEncryption"`
	// Prevent location from use as a source.
	IsTarget *bool `json:"isTarget" xml:"isTarget"`
	// The limit during off-peak hours, expressed in total number of bytes per second.  Specify 0 for no limit.
	OffPeakBytesPerSecondLimit *float64 `json:"offPeakBytesPerSecondLimit,omitempty" xml:"offPeakBytesPerSecondLimit"`
	// The file scan limit during off-peak hours, expressed in total number of files per second. Specify 0 for no limit.
	OffPeakFilesPerSecondScanLimit *float64 `json:"offPeakFilesPerSecondScanLimit,omitempty" xml:"offPeakFilesPerSecondScanLimit"`
	// The limit during peak hours, expressed in total number of bytes per second.  Specify 0 for no limit.
	PeakBytesPerSecondLimit *float64 `json:"peakBytesPerSecondLimit,omitempty" xml:"peakBytesPerSecondLimit"`
	// The file scan limit during peak hours, expressed in total number of files per second. Specify 0 for no limit.
	PeakFilesPerSecondScanLimit *float64 `json:"peakFilesPerSecondScanLimit,omitempty" xml:"peakFilesPerSecondScanLimit"`
	// A list of the days of the week where rate limits are enforced during peak and off-peak times.  If a day of week is not in the list, it is assumed to be unlimited.
	PeakTimesSchedule *[]ApiPeakTimeSchedule `json:"peakTimesSchedule,omitempty" xml:"peakTimesSchedule"`
	// The number of days to retain files on this target before scheduling files for deletion. This field is only applicable to targets.
	RetentionDays *int32 `json:"retentionDays,omitempty" xml:"retentionDays"`
	// For use only with AmazonS3 Glacier.  The URL of the endpoint to which the server should connect to access the storage.
	S3Endpoint *string `json:"s3Endpoint,omitempty" xml:"s3Endpoint"`
	// For use only with AmazonS3 Glacier.  The AmazonS3 Glacier region in which to connect.  If empty, the default region is assumed.
	S3Region *string `json:"s3Region,omitempty" xml:"s3Region"`
	// For use only with S3 emulators.  Will ignore SSL certificate errors (self signed certificates).
	IgnoreSSL *bool `json:"ignoreSSL,omitempty" xml:"ignoreSSL"`
	// For use only with AmazonS3 Glacier.  The secret access key of the credentials for AmazonS3 Glacier. This is write-only.
	SecretAccessKey *string `json:"secretAccessKey" xml:"secretAccessKey"`
	Type *string `json:"type" xml:"type"`
}
