/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// GENERATED BY JK -- Not part of OpenAPI

package openapi
import (
	"time"
)

type ApiManifestFilesPaginator struct {
	ResultLimit int64 `json:"ResultLimit" xml:"ResultLimit"`
	ResultOffset int64 `json:"ResultOffset" xml:"ResultOffset"`
	Timestamp time.Time `json:"Timestamp" xml:"Timestamp"`
	TotalResults int64 `json:"TotalResults" xml:"TotalResults"`
	Data []ApiManifestFile `json:"data" xml:"data"`
}
