/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
import (
	"time"
)
// ApiStorageLocation struct for ApiStorageLocation
type ApiStorageLocation struct {
	// For use only with BlackPearl, S3 or MSAzure.  The access key ID of the credentials for BlackPearl, S3 or MS Azure.
	AccessKeyId *string `json:"accessKeyId,omitempty" xml:"accessKeyId"`
	// Used to re-activate a 'deleted' storage location.
	Active *bool `json:"active,omitempty" xml:"active"`
	// Sources can have an adGroup name associated with them to restrict access to users not in the group.
	ADGroup *string `json:"aDGroup,omitempty" xml:"aDGroup"`
	// For use only with BlackPearl.  The URL of the BlackPearl server data port.
	SpectraDataEndpoint *string `json:"spectraDataEndpoint,omitempty" xml:"spectraDataEndpoint"`
	// For use only with BlackPearl or SpectraNAS.  The URL of the BlackPearl server management port.
	SpectraMgmtEndpoint *string `json:"spectraMgmtEndpoint,omitempty" xml:"spectraMgmtEndpoint"`
	// For use only with BlackPearl or SpectraNAS.  The password to login to the management port.  This is write-only.
	SpectraPassword *string `json:"spectraPassword,omitempty" xml:"spectraPassword"`
	// For use only with BlackPearl or SpectraNAS.  The username to login to the management port.
	SpectraUsername *string `json:"spectraUsername,omitempty" xml:"spectraUsername"`
	// Used for BlackPearl and S3/Archive endpoints.  The bucket/vault to use for storage.
	Bucket *string `json:"bucket,omitempty" xml:"bucket"`
	// Used for specifying existing BlackPearl data policies.
	BucketPolicyId *string `json:"bucketPolicyId,omitempty" xml:"bucketPolicyId"`
	// Total number of bytes transferred to/from this location. This field is read-only.
	BytesTransferredIn *int64 `json:"bytesTransferredIn,omitempty" xml:"bytesTransferredIn"`
	// Total number of bytes transferred to/from this location. This field is read-only.
	BytesTransferredOut *int64 `json:"bytesTransferredOut,omitempty" xml:"bytesTransferredOut"`
	// True if location is currently connected to the server.  This field is read-only.
	Connected *bool `json:"connected,omitempty" xml:"connected"`
	// Cost per TB of storage in units of department currency.  Only valid when Department is set.
	CostPerTB *float32 `json:"costPerTB,omitempty" xml:"costPerTB"`
	// Time when storage location was created.  This field is read-only.
	Created *time.Time `json:"created,omitempty" xml:"created"`
	// ID of department responsible for location storage cost.
	Department *string `json:"department,omitempty" xml:"department"`
	// Description of the storage location.
	Description *string `json:"description,omitempty" xml:"description"`
	// Used to enable encryption that has been configured for the product.
	EnableEncryption *bool `json:"enableEncryption,omitempty" xml:"enableEncryption"`
	// For use only with SpectraNAS. Used to enable snapshots on the SpectraNAS device.
	EnableSnapshots *bool `json:"enableSnapshots,omitempty" xml:"enableSnapshots"`
	// Total number of bytes transferred to/from this location. This field is read-only.
	FilesTransferredIn *int64 `json:"filesTransferredIn,omitempty" xml:"filesTransferredIn"`
	// Total number of bytes transferred to/from this location. This field is read-only.
	FilesTransferredOut *int64 `json:"filesTransferredOut,omitempty" xml:"filesTransferredOut"`
	// Prevent location from use as a source. Set to true for BlackPearl.
	IsTarget *bool `json:"isTarget" xml:"isTarget"`
	// For use only with SpectraNAS. Used to keep the SpectraNAS device in a Read-Only state after a job completes.
	KeepReadOnly *bool `json:"keepReadOnly,omitempty" xml:"keepReadOnly"`
	// Time when storage location was last accessed.  This field is read-only.
	LastAccess *time.Time `json:"lastAccess,omitempty" xml:"lastAccess"`
	// Time when storage location was last scanned for files.  This field is read-only.
	LastScan *time.Time `json:"lastScan,omitempty" xml:"lastScan"`
	// Storage location name.  This is the location ID.
	Name *string `json:"name,omitempty" xml:"name"`
	// The limit during off-peak hours, expressed in total number of bytes per second.  Specify 0 for no limit.
	OffPeakBytesPerSecondLimit *float64 `json:"offPeakBytesPerSecondLimit,omitempty" xml:"offPeakBytesPerSecondLimit"`
	// The file scan limit during off-peak hours, expressed in total number of files per second. Specify 0 for no limit.
	OffPeakFilesPerSecondScanLimit *float64 `json:"offPeakFilesPerSecondScanLimit,omitempty" xml:"offPeakFilesPerSecondScanLimit"`
	// How archived data should be packed.  This cannot be set on NAS locations. Default is None.
	PackingType *string `json:"packingType,omitempty" xml:"packingType"`
	// Used for NAS source/target and S3 source locations, this is the filesystem path to the NAS mount point and optionally the prefix for S3 path matching.
	Path *string `json:"path,omitempty" xml:"path"`
	// The limit during peak hours, expressed in total number of bytes per second.  Specify 0 for no limit.
	PeakBytesPerSecondLimit *float64 `json:"peakBytesPerSecondLimit,omitempty" xml:"peakBytesPerSecondLimit"`
	// The file scan limit during peak hours, expressed in total number of files per second. Specify 0 for no limit.
	PeakFilesPerSecondScanLimit *float64 `json:"peakFilesPerSecondScanLimit,omitempty" xml:"peakFilesPerSecondScanLimit"`
	// A list of the days of the week where rate limits are enforced during peak and off-peak times.  If a day of week is not in the list, it is assumed to be unlimited.
	PeakTimesSchedule *[]ApiPeakTimeSchedule `json:"peakTimesSchedule,omitempty" xml:"peakTimesSchedule"`
	// The number of days to retain files on this target before scheduling files for deletion. This field is only applicable to targets.
	RetentionDays *int32 `json:"retentionDays" xml:"retentionDays"`
	// For use only with Amazon S3 or S3 emulators.  The URL of the endpoint to which the server should connect to access the storage.
	S3Endpoint *string `json:"s3Endpoint,omitempty" xml:"s3Endpoint"`
	// For use only with Amazon S3 or S3 emulators.  The S3 region in which to connect.  If empty, the default region is assumed.
	S3Region *string `json:"s3Region,omitempty" xml:"s3Region"`
	// For use only with S3 emulators.  Will ignore SSL certificate errors (self signed certificates).
	IgnoreSSL *bool `json:"ignoreSSL,omitempty" xml:"ignoreSSL"`
	// For use only with BlackPearl, S3 or MSAzure.  The secret access key of the credentials for BlackPearl, S3 or MS Azure. This is write-only.
	SecretAccessKey *string `json:"secretAccessKey,omitempty" xml:"secretAccessKey"`
	Type *string `json:"type" xml:"type"`
}
