/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2023 Spectra Logic Corporation
 *
 * API version: 0.2
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"time"
)
// ApiFileObject struct for ApiFileObject
type ApiFileObject struct {
	Path string `json:"path,omitempty" xml:"path"`
	LocationPath string `json:"locationPath,omitempty" xml:"locationPath"`
	Directory string `json:"directory,omitempty" xml:"directory"`
	Name string `json:"name,omitempty" xml:"name"`
	IsDirectory bool `json:"isDirectory,omitempty" xml:"isDirectory"`
	Size int64 `json:"size,omitempty" xml:"size"`
	RecordTime time.Time `json:"recordTime,omitempty" xml:"recordTime"`
	Created time.Time `json:"created,omitempty" xml:"created"`
	Modified time.Time `json:"modified,omitempty" xml:"modified"`
	Accessed time.Time `json:"accessed,omitempty" xml:"accessed"`
	Hash string `json:"hash,omitempty" xml:"hash"`
	Pack string `json:"pack,omitempty" xml:"pack"`
	ArchiveId string `json:"archiveId,omitempty" xml:"archiveId"`
	VersionId int64 `json:"versionId,omitempty" xml:"versionId"`
	Tags []string `json:"tags,omitempty" xml:"tags"`
}
