/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
import (
	"time"
)
// ApiStorageLocationPaginator struct for ApiStorageLocationPaginator
type ApiStorageLocationPaginator struct {
	ResultLimit int64 `json:"ResultLimit" xml:"ResultLimit"`
	ResultOffset int64 `json:"ResultOffset" xml:"ResultOffset"`
	Timestamp time.Time `json:"Timestamp" xml:"Timestamp"`
	TotalResults int64 `json:"TotalResults" xml:"TotalResults"`
	Data []ApiStorageLocation `json:"data" xml:"data"`
}
