/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// GENERATED BY JK -- NOT PART OF OPENAPI

package openapi
// ApiProject struct for ApiProject
type ApiManifestFile struct {
	Name *string `json:"name" xml:"name"`
	Path  *string `json:"path,omitempty" xml:"path"`
	Checksum *string `json:"hash,omitempty" xml:"hash"`
	Size *int64 `json:"size,omitempty" xml:"size"`
}

func MakeApiManifestFile(name string, path string) *ApiManifestFile{
	return &ApiManifestFile{
		Name: &name,
		Path: &path,
		Checksum: nil,
		Size: nil,
	}
}
