/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
import (
	"time"
)
// ApiProjectStatus Status of the project. All values are read only.
type ApiProjectStatus struct {
	// The name of the project. This cannot be modified.
	Name *string `json:"name,omitempty" xml:"name"`
	// Time when the project was created.  This is set automatically and is read-only.
	Created *time.Time `json:"created,omitempty" xml:"created"`
	// The user that created the project.  This is set automatically and is read-only.
	CreatedBy *string `json:"createdBy,omitempty" xml:"createdBy"`
	// The time the project information was last updated.  This is set automatically and is read-only.
	Updated *time.Time `json:"updated,omitempty" xml:"updated"`
	// The user that last updated the project.  This is set automatically and is read-only.
	UpdatedBy *string `json:"updatedBy,omitempty" xml:"updatedBy"`
	// Time when a job last ran for this project.  This is set automatically and is read-only.
	LastJobRunTime *time.Time `json:"lastJobRunTime,omitempty" xml:"lastJobRunTime"`
	// End time of most recent successful job for this project.  This is set automatically and is read-only.
	LastSuccessfulJob *time.Time `json:"lastSuccessfulJob,omitempty" xml:"lastSuccessfulJob"`
	// If the last attempt to run the project ran into a conflict with an existing job, this will be set. This is set automatically and is read-only.
	ConflictDetected *time.Time `json:"conflictDetected,omitempty" xml:"conflictDetected"`
	// The next time this project is scheduled to run. This is set automatically and is read-only.
	NextRunTime *time.Time `json:"nextRunTime,omitempty" xml:"nextRunTime"`
}
