/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// GENERATED BY JK -- NOT PART OF OPENAPI

package openapi

import "time"

type ApiJob struct {
	// Job name.
	Name *string `json:"name" xml:"name"`
	// Project name.
	Project *string `json:"project,omitempty" xml:"project"`
	// The source share with which the project will work. This is not required when updating the project.
	Description *string `json:"description,omitempty" xml:"description"`
	// Filenames for object search
	Filenames *[]string `json:"filenames,omitempty" xml:"filenames"`
	// Tags.
	Tags *[]string `json:"tags,omitempty" xml:"tags"`
}

func MakeApiJob(name string, files []string) *ApiJob {
	return &ApiJob{
		Name: &name,
		Description: nil,
		Filenames: &files,
		Tags: nil,
	}
}

type ApiJobStatus struct {
	Name *string `json:"job" xml:"job"`
	PercentComplete *float32 `json:"percentComplete" xml:"percentComplete"`
	State *string `json:"state" xml:state"`
}

type ApiJobWithState struct {
	Name *string `json:"name" xml:"name"`
	Project *string `json:"task,omitempty" xml:"task"`
	Description *string `json:"description,omitempty" xml:"description"`
	PercentComplete *float32 `json:"percentComplete" xml:"percentComplete"`
	State *string `json:"state" xml:state"`
	Tags *[]string `json:"tags,omitempty" xml:"tags"`
}

type ApiJobsWithStatusPaginator struct {
	ResultLimit int64 `json:"ResultLimit" xml:"ResultLimit"`
	ResultOffset int64 `json:"ResultOffset" xml:"ResultOffset"`
	Timestamp time.Time `json:"Timestamp" xml:"Timestamp"`
	TotalResults int64 `json:"TotalResults" xml:"TotalResults"`
	Data []ApiJobWithState `json:"data" xml:"data"`
}
