/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// GENERATED BY JK -- NOT PART OF OPENAPI

package openapi

// ApiProject struct for ApiProject
type ApiManifestFile struct {
	Name       *string `json:"name" xml:"name"`
	Path       *string `json:"path,omitempty" xml:"path"`
	IsDir      *bool   `json:"isDirectory,omitempty" xml:"isDirectory"`
	Checksum   *string `json:"hash,omitempty" xml:"hash"`
	Size       *int64  `json:"size,omitempty" xml:"size"`
	RecordTime *string `json:"recordTime,omitempty" xml:"recordTime"`
}

func MakeApiManifestFile(name string, path string, isDir bool) *ApiManifestFile {
	return &ApiManifestFile{
		Name:     &name,
		Path:     &path,
		IsDir:    &isDir,
		Checksum: nil,
		Size:     nil,
	}
}
