/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2023 Spectra Logic Corporation
 *
 * API version: 0.2
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
// ApiCriteria Complex filter criteria for a search operation. See https://storcycle.spectrawiki.com/en/administration/api for more information
type ApiCriteria struct {
	Version string `json:"version,omitempty" xml:"version"`
	Logicaloperation string `json:"logicaloperation,omitempty" xml:"logicaloperation"`
	Field string `json:"field,omitempty" xml:"field"`
	Comparator string `json:"comparator,omitempty" xml:"comparator"`
	Value map[string]interface{} `json:"value,omitempty" xml:"value"`
	Pinned string `json:"pinned,omitempty" xml:"pinned"`
	Criteria []ApiCriteria `json:"criteria,omitempty" xml:"criteria"`
}

