/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2023 Spectra Logic Corporation
 *
 * API version: 0.2
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
// ApiBrowseArchivedCriteria Browse archived data using criteria.
type ApiBrowseArchivedCriteria struct {
	// The directory to start from.
	Directory *string `json:"directory,omitempty" xml:"directory"`
	// Descend the directory tree without restriction. Enabling can delay results substantially.
	Unrestricted *bool `json:"unrestricted,omitempty" xml:"unrestricted"`
	Criteria ApiCriteria `json:"criteria,omitempty" xml:"criteria"`
}

