/*
 * Spectra Logic Corporation Software
 *
 * StorCycle® REST API Copyright © 2020 Spectra Logic Corporation
 *
 * API version: 0.1
 * Contact: developer@spectralogic.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
// ApiProjectFilter Filter to limit operations to a set of files based on location.
type ApiProjectFilter struct {
	// Directories to exclude.
	ExcludeDirectories *[]string `json:"excludeDirectories,omitempty" xml:"excludeDirectories"`
	// File types to exclude.
	ExcludeFileTypes *[]string `json:"excludeFileTypes,omitempty" xml:"excludeFileTypes"`
	// Directories to include.  Specifying include directories will exclude any directories not explicitly identified here.
	IncludeDirectories *[]string `json:"includeDirectories,omitempty" xml:"includeDirectories"`
	// File types to include. Specifying include file types will exclude any file types not explicitly identified here.
	IncludeFileTypes *[]string `json:"includeFileTypes,omitempty" xml:"includeFileTypes"`
	// The minimum age of files with which this project will work.  Default is AnyAge.
	MinimumAge *string `json:"minimumAge,omitempty" xml:"minimumAge"`
	// The number of days old a file must equal or exceed for it to be processed by the job. This is only valid if CustomAge was selected for minimumAge.
	CustomAgeInDays *int32 `json:"customAgeInDays,omitempty" xml:"customAgeInDays"`
	// The minimum size of files with which this project will work. Default is Any.
	MinimumSize *string `json:"minimumSize,omitempty" xml:"minimumSize"`
}
